#!/bin/sh

# local debug
# DOCKER_TAG=$1

# $DOCKER_TAG is in the format LINUX_BASE--NODE_VERSION
# split on -- on 2 variables
DOCKER_TAG_0=${DOCKER_TAG%%--*}
DOCKER_TAG_1=${DOCKER_TAG#*--}

# replace underscore with /
LINUX_BASE=$(echo $DOCKER_TAG_0 | sed -e "s/_/:/g")
NODE_VERSION=$DOCKER_TAG_1
echo DOCKER_TAG is $DOCKER_TAG
echo LINUX_BASE is ${LINUX_BASE}
echo NODE_VERSION is $NODE_VERSION

docker build \
  --build-arg linux_base=$LINUX_BASE \
  --build-arg node_version=$NODE_VERSION \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .

